import { NextResponse } from 'next/server';

interface InquiryFormData {
  name: string;
  email: string;
  phone: string;
}

export async function POST(request: Request) {
  try {
    const body: InquiryFormData = await request.json();

    // Validate required fields
    if (!body.name || !body.email || !body.phone) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(body.email)) {
      return NextResponse.json(
        { error: 'Invalid email address' },
        { status: 400 }
      );
    }

    // Check if Resend API key is configured
    const resendApiKey = process.env.RESEND_API_KEY;
    if (!resendApiKey) {
      console.warn('Resend API key not configured. Email feature disabled.');
      return NextResponse.json(
        {
          success: true,
          message: 'Inquiry received (email service not configured)',
        },
        { status: 200 }
      );
    }

    // Send email using Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${resendApiKey}`,
      },
      body: JSON.stringify({
        from: 'noreply@clarivex.com',
        to: 'darinlutz648@yahoo.com',
        subject: 'Clarivex inquiry',
        html: `
          <div style="font-family: Arial, sans-serif; background-color: #0f172a; color: #f1f5f9; padding: 20px;">
            <div style="max-width: 600px; margin: 0 auto; background-color: #1e293b; border: 1px solid #87ceeb; border-radius: 8px; padding: 20px;">
              <h2 style="color: #87ceeb; margin-bottom: 20px;">Clarivex Inquiry</h2>

              <div style="margin-bottom: 15px;">
                <strong style="color: #b0e0e6;">Full Name:</strong>
                <p style="margin: 5px 0; color: #e2e8f0;">${escapeHtml(body.name)}</p>
              </div>

              <div style="margin-bottom: 15px;">
                <strong style="color: #b0e0e6;">Email:</strong>
                <p style="margin: 5px 0; color: #e2e8f0;">
                  <a href="mailto:${escapeHtml(body.email)}" style="color: #87ceeb; text-decoration: none;">
                    ${escapeHtml(body.email)}
                  </a>
                </p>
              </div>

              <div style="margin-bottom: 15px;">
                <strong style="color: #b0e0e6;">Phone:</strong>
                <p style="margin: 5px 0; color: #e2e8f0;">
                  <a href="tel:${escapeHtml(body.phone)}" style="color: #87ceeb; text-decoration: none;">
                    ${escapeHtml(body.phone)}
                  </a>
                </p>
              </div>

              <hr style="border: none; border-top: 1px solid #087cea; margin: 20px 0;">

              <p style="font-size: 12px; color: #64748b;">
                This email was generated by the Clarivex contact page.
              </p>
            </div>
          </div>
        `,
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      console.error('Resend API error:', error);

      return NextResponse.json(
        {
          success: true,
          message: 'Your inquiry has been received',
        },
        { status: 200 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        message: 'Your inquiry has been sent successfully',
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Inquiry form error:', error);

    return NextResponse.json(
      { error: 'Failed to process your request' },
      { status: 500 }
    );
  }
}

// Helper function to escape HTML
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}
