import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { isUniqueViolation, query, transaction } from './db';

const scryptAsync = promisify(scrypt) as (password: string, salt: Buffer, keylen: number) => Promise<Buffer>;

const KEY_LENGTH = 64;

export type User = {
  id: number;
  firstName: string;
  lastName: string;
  emailAddress: string;
  accountStatus: string;
  signupDate: string | null;
  subscriptionEndDate: string | null;
  stripeSubscriptionId: string | null;
  level: number;
};

const USER_COLUMNS =
  'id, first_name, last_name, email_address, account_status, signup_date, subscription_end_date, stripe_subscription_id, level';

// Dates are stored as ISO 8601 UTC strings, so they compare correctly as text.
// One month from `from`, clamped so Jan 31 becomes Feb 28/29 rather than Mar 3.
export function oneMonthFrom(from: Date = new Date()): string {
  const end = new Date(from);
  end.setUTCDate(1);
  end.setUTCMonth(end.getUTCMonth() + 1);
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  end.setUTCDate(Math.min(from.getUTCDate(), lastDay));
  return end.toISOString();
}

function hasEnded(user: User): boolean {
  return !user.subscriptionEndDate || user.subscriptionEndDate < new Date().toISOString();
}

export function canSubscribe(user: User): boolean {
  return (
    user.accountStatus === 'New' ||
    user.accountStatus === 'Expired' ||
    (user.accountStatus === 'Canceled' && hasEnded(user))
  );
}

export class EmailTakenError extends Error {
  constructor() {
    super('An account with that email address already exists');
  }
}

let schemaReady: Promise<void> | null = null;

export function ensureUserSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = transaction(async (client) => {
      // Concurrent CREATE TABLE IF NOT EXISTS can still collide in Postgres
      // when several server instances boot at once, so serialize them.
      await client.query("SELECT pg_advisory_xact_lock(hashtext('clarivex_user_schema'))");
      await client.query(`CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        password TEXT NOT NULL,
        account_status TEXT NOT NULL DEFAULT 'New',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        signup_date TEXT,
        subscription_end_date TEXT
      )`);
      // Added after launch. The column is created with DEFAULT 2 so every
      // user who existed at that point gets Level 2; new signups start at 0.
      await client.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 2');
      await client.query('ALTER TABLE users ALTER COLUMN level SET DEFAULT 0');
      // Email addresses are unique regardless of case
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS users_email_address_key ON users (lower(email_address))'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS users_stripe_subscription_id_idx ON users (stripe_subscription_id)'
      );
      await client.query(`CREATE TABLE IF NOT EXISTS sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id)');
      await client.query(`CREATE TABLE IF NOT EXISTS password_resets (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS password_resets_user_id_idx ON password_resets (user_id)');
    }).catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

// Stored as "scrypt$<salt hex>$<hash hex>" so the format is self-describing.
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, 'hex');
  const actual = await scryptAsync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return timingSafeEqual(actual, expected);
}

function rowToUser(row: Record<string, unknown>): User {
  return {
    id: Number(row.id),
    firstName: row.first_name as string,
    lastName: row.last_name as string,
    emailAddress: row.email_address as string,
    accountStatus: row.account_status as string,
    signupDate: (row.signup_date as string | null) ?? null,
    subscriptionEndDate: (row.subscription_end_date as string | null) ?? null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) ?? null,
    level: Number(row.level ?? 0),
  };
}

export async function createUser(input: {
  firstName: string;
  lastName: string;
  emailAddress: string;
  password: string;
}): Promise<User> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(input.password);
  try {
    const rows = await query(
      `INSERT INTO users (first_name, last_name, email_address, password, account_status, signup_date, level)
       VALUES ($1, $2, $3, $4, 'New', $5, 0)
       RETURNING ${USER_COLUMNS}`,
      [input.firstName, input.lastName, input.emailAddress, passwordHash, new Date().toISOString()]
    );
    return rowToUser(rows[0]);
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new EmailTakenError();
    }
    throw error;
  }
}

// Returns the user only when the email exists and the password matches.
export async function authenticateUser(emailAddress: string, password: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(
    `SELECT ${USER_COLUMNS}, password FROM users WHERE lower(email_address) = lower($1)`,
    [emailAddress]
  );
  if (!row) return null;
  const ok = await verifyPassword(password, row.password as string);
  return ok ? rowToUser(row) : null;
}

export async function getUserByEmail(emailAddress: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM users WHERE lower(email_address) = lower($1)`, [
    emailAddress,
  ]);
  return row ? rowToUser(row) : null;
}

// Also signs the user out everywhere, since an old session may belong to
// whoever knew the previous password.
export async function updatePassword(userId: number, password: string): Promise<void> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(password);
  await transaction(async (client) => {
    await client.query('UPDATE users SET password = $1 WHERE id = $2', [passwordHash, userId]);
    await client.query('DELETE FROM sessions WHERE user_id = $1', [userId]);
  });
}

export async function getUserById(id: number): Promise<User | null> {
  await ensureUserSchema();
  // A paid subscription whose end date has passed (e.g. a failed renewal) is expired
  await query(
    `UPDATE users SET account_status = 'Expired'
     WHERE id = $1 AND account_status = 'Active' AND subscription_end_date < $2`,
    [id, new Date().toISOString()]
  );
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM users WHERE id = $1`, [id]);
  return row ? rowToUser(row) : null;
}

// Links a completed Checkout Session to the user who started it.
export async function startSubscription(
  userId: number,
  stripeCustomerId: string,
  stripeSubscriptionId: string
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE users SET stripe_customer_id = $1, stripe_subscription_id = $2, account_status = 'Active',
       subscription_end_date = $3
     WHERE id = $4`,
    [stripeCustomerId, stripeSubscriptionId, oneMonthFrom(), userId]
  );
}

// A paid Lifetime purchase never expires. Clearing the subscription ID keeps
// events from an earlier monthly subscription from changing the status.
export async function grantLifetimeAccess(
  userId: number,
  stripeCustomerId: string | null
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE users SET account_status = 'Paid', subscription_end_date = NULL,
       stripe_subscription_id = NULL, stripe_customer_id = COALESCE($1, stripe_customer_id)
     WHERE id = $2`,
    [stripeCustomerId, userId]
  );
}

// Called on each successful monthly renewal payment.
export async function renewSubscription(stripeSubscriptionId: string): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE users SET account_status = 'Active', subscription_end_date = $1
     WHERE stripe_subscription_id = $2`,
    [oneMonthFrom(), stripeSubscriptionId]
  );
}

export async function setStatusBySubscriptionId(
  stripeSubscriptionId: string,
  accountStatus: string
): Promise<void> {
  await ensureUserSchema();
  await query('UPDATE users SET account_status = $1 WHERE stripe_subscription_id = $2', [
    accountStatus,
    stripeSubscriptionId,
  ]);
}
