import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { isUniqueViolation, query, transaction } from './db';
import { ROLES } from './roles';
import { ACCOUNT_STATUS, canBuyPlan } from './accountStatus';

const scryptAsync = promisify(scrypt) as (password: string, salt: Buffer, keylen: number) => Promise<Buffer>;

const KEY_LENGTH = 64;

export type User = {
  id: number;
  userName: string;
  emailAddress: string;
  accountStatus: string;
  signupDate: string | null;
  subscriptionEndDate: string | null;
  stripeSubscriptionId: string | null;
  // One of ROLES
  role: string;
};

const USER_COLUMNS =
  'id, user_name, email_address, account_status, signup_date, subscription_end_date, stripe_subscription_id, role';

// Dates are stored as ISO 8601 UTC strings, so they compare correctly as text.
// One month from `from`, clamped so Jan 31 becomes Feb 28/29 rather than Mar 3.
export function oneMonthFrom(from: Date = new Date()): string {
  const end = new Date(from);
  end.setUTCDate(1);
  end.setUTCMonth(end.getUTCMonth() + 1);
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  end.setUTCDate(Math.min(from.getUTCDate(), lastDay));
  return end.toISOString();
}

export function canBuy(user: User, plan: 'monthly' | 'lifetime'): boolean {
  return canBuyPlan(user.accountStatus, plan);
}

export class EmailTakenError extends Error {
  constructor() {
    super('An account with that email address already exists');
  }
}

let schemaReady: Promise<void> | null = null;

export function ensureUserSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = transaction(async (client) => {
      // Concurrent CREATE ... IF NOT EXISTS can still collide in Postgres
      // when several server instances boot at once, so serialize them.
      await client.query("SELECT pg_advisory_xact_lock(hashtext('clarivex_user_schema'))");
      // Accounts, sign-in sessions and password reset links live in their own
      // schema. They started over empty there; the old tables in public
      // aren't used anymore.
      await client.query('CREATE SCHEMA IF NOT EXISTS clarivexwebsite');
      await client.query(`CREATE TABLE IF NOT EXISTS clarivexwebsite."ClarivexUsers" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        password TEXT NOT NULL,
        account_status TEXT NOT NULL DEFAULT '${ACCOUNT_STATUS.unsubscribed}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        signup_date TEXT,
        subscription_end_date TEXT,
        role TEXT NOT NULL DEFAULT '${ROLES.unsubscribed}'
      )`);
      // Email addresses are unique regardless of case
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS clarivex_users_email_address_key ON clarivexwebsite."ClarivexUsers" (lower(email_address))'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS clarivex_users_stripe_subscription_id_idx ON clarivexwebsite."ClarivexUsers" (stripe_subscription_id)'
      );
      await client.query(`CREATE TABLE IF NOT EXISTS clarivexwebsite.sessions (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES clarivexwebsite."ClarivexUsers"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON clarivexwebsite.sessions (user_id)');
      await client.query(`CREATE TABLE IF NOT EXISTS clarivexwebsite.password_resets (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES clarivexwebsite."ClarivexUsers"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS password_resets_user_id_idx ON clarivexwebsite.password_resets (user_id)'
      );
    }).catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

// Stored as "scrypt$<salt hex>$<hash hex>" so the format is self-describing.
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, 'hex');
  const actual = await scryptAsync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return timingSafeEqual(actual, expected);
}

function rowToUser(row: Record<string, unknown>): User {
  return {
    id: Number(row.id),
    userName: row.user_name as string,
    emailAddress: row.email_address as string,
    accountStatus: row.account_status as string,
    role: row.role as string,
    signupDate: (row.signup_date as string | null) ?? null,
    subscriptionEndDate: (row.subscription_end_date as string | null) ?? null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) ?? null,
  };
}

// The site owner is made Admin on sign-up; everyone else starts Unsubscribed
const OWNER_EMAIL = 'darinlutz@yahoo.com';

function initialRole(emailAddress: string): string {
  return emailAddress.trim().toLowerCase() === OWNER_EMAIL ? ROLES.admin : ROLES.unsubscribed;
}

export async function createUser(input: {
  userName: string;
  emailAddress: string;
  password: string;
}): Promise<User> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(input.password);
  try {
    const rows = await query(
      `INSERT INTO clarivexwebsite."ClarivexUsers" (user_name, email_address, password, account_status, signup_date, role)
       VALUES ($1, $2, $3, $6, $4, $5)
       RETURNING ${USER_COLUMNS}`,
      [input.userName, input.emailAddress, passwordHash, new Date().toISOString(), initialRole(input.emailAddress), ACCOUNT_STATUS.unsubscribed]
    );
    return rowToUser(rows[0]);
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new EmailTakenError();
    }
    throw error;
  }
}

// Returns the user only when the email exists and the password matches.
export async function authenticateUser(emailAddress: string, password: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(
    `SELECT ${USER_COLUMNS}, password FROM clarivexwebsite."ClarivexUsers" WHERE lower(email_address) = lower($1)`,
    [emailAddress]
  );
  if (!row) return null;
  const ok = await verifyPassword(password, row.password as string);
  return ok ? rowToUser(row) : null;
}

export async function getUserByEmail(emailAddress: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM clarivexwebsite."ClarivexUsers" WHERE lower(email_address) = lower($1)`, [
    emailAddress,
  ]);
  return row ? rowToUser(row) : null;
}

// Also signs the user out everywhere, since an old session may belong to
// whoever knew the previous password.
export async function updatePassword(userId: number, password: string): Promise<void> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(password);
  await transaction(async (client) => {
    await client.query('UPDATE clarivexwebsite."ClarivexUsers" SET password = $1 WHERE id = $2', [passwordHash, userId]);
    await client.query('DELETE FROM clarivexwebsite.sessions WHERE user_id = $1', [userId]);
  });
}

export async function getUserById(id: number): Promise<User | null> {
  await ensureUserSchema();
  // A monthly subscription whose end date has passed (e.g. a failed renewal) is expired
  await query(
    `UPDATE clarivexwebsite."ClarivexUsers" SET account_status = $3
     WHERE id = $1 AND account_status = $4 AND subscription_end_date < $2`,
    [id, new Date().toISOString(), ACCOUNT_STATUS.expired, ACCOUNT_STATUS.monthly]
  );
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM clarivexwebsite."ClarivexUsers" WHERE id = $1`, [id]);
  return row ? rowToUser(row) : null;
}

// SQL for setting role to the given parameter, except that Admins stay Admin
const KEEP_ADMIN_ELSE = (param: string) => `CASE WHEN role = '${ROLES.admin}' THEN role ELSE ${param} END`;

// Links a completed Checkout Session to the user who started it.
export async function startSubscription(
  userId: number,
  stripeCustomerId: string,
  stripeSubscriptionId: string
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE clarivexwebsite."ClarivexUsers" SET stripe_customer_id = $1, stripe_subscription_id = $2, account_status = $6,
       subscription_end_date = $3, role = ${KEEP_ADMIN_ELSE('$5')}
     WHERE id = $4`,
    [stripeCustomerId, stripeSubscriptionId, oneMonthFrom(), userId, ROLES.monthly, ACCOUNT_STATUS.monthly]
  );
}

// A paid Lifetime purchase never expires. Clearing the subscription ID keeps
// events from an earlier monthly subscription from changing the status.
// Returns that earlier monthly subscription's ID, if any, so the caller can
// cancel it in Stripe.
export async function grantLifetimeAccess(
  userId: number,
  stripeCustomerId: string | null
): Promise<string | null> {
  await ensureUserSchema();
  const [row] = await query(
    `UPDATE clarivexwebsite."ClarivexUsers" SET account_status = $4, subscription_end_date = NULL,
       stripe_subscription_id = NULL, stripe_customer_id = COALESCE($1, "ClarivexUsers".stripe_customer_id),
       role = CASE WHEN "ClarivexUsers".role = '${ROLES.admin}' THEN "ClarivexUsers".role ELSE $3 END
     FROM (SELECT id, stripe_subscription_id FROM clarivexwebsite."ClarivexUsers" WHERE id = $2) AS previous
     WHERE "ClarivexUsers".id = previous.id
     RETURNING previous.stripe_subscription_id AS previous_subscription_id`,
    [stripeCustomerId, userId, ROLES.lifetime, ACCOUNT_STATUS.lifetime]
  );
  return (row?.previous_subscription_id as string | null | undefined) ?? null;
}

// Called on each successful monthly renewal payment.
export async function renewSubscription(stripeSubscriptionId: string): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE clarivexwebsite."ClarivexUsers" SET account_status = $3, subscription_end_date = $1
     WHERE stripe_subscription_id = $2`,
    [oneMonthFrom(), stripeSubscriptionId, ACCOUNT_STATUS.monthly]
  );
}

export async function setStatusBySubscriptionId(
  stripeSubscriptionId: string,
  accountStatus: string
): Promise<void> {
  await ensureUserSchema();
  await query('UPDATE clarivexwebsite."ClarivexUsers" SET account_status = $1 WHERE stripe_subscription_id = $2', [
    accountStatus,
    stripeSubscriptionId,
  ]);
}
